#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2024.3.2.1"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
#     "all",
     "apriltag",
     "commands2",
    "cscore",
     "navx",
     "pathplannerlib",
    # "phoenix5",
    # "phoenix6",
     "playingwithfusion",
     "rev",
    # "romi",
     "sim",
    # "xrp",
]

# idk why this works but I got the idea from 4774 -LHACK
dependencies = [
     "photonlibpy"
]

# Other pip packages to install
requires = [
     "photonlibpy"
#    "robotpy-commands-v2==2024.0.0b4"
]
